banckproject/banckapp/urls.py
from django.urls import path

from . import views

app_name='banckapp'

urlpatterns=[
    path('', views.index,name='index'),
    path('new/',views.new,name='new'),
    path('add/',views.person_create_view, name='person_add'),
    path('ajax/load-areas/',views.load_areas, name='ajax_load_areas'),
    path('submit/',views.submit,name='submit'),
]

banckproject/banckproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from banckproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('banckapp.urls')),
    path('credential/',include('credential_app.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root= settings.MEDIA_ROOT)

banckproject/credential_app/urls.py
from django.urls import path

from . import views

app_name='credentials'

urlpatterns =[
		path('register',views.register, name='register'),
		path('login',views.login, name='login'),
        path('logout/', views.logout,name='logout')
	]

banckproject/banckapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    link=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='district'
        verbose_name_plural='districts'

    def __str__(self):
        return '{}'.format(self.name)

class Branch(models.Model):
    district=models.ForeignKey(District,on_delete=models.CASCADE)
    slug=models.SlugField(max_length=250,unique=True)
    area=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('area',)
        verbose_name='branch'
        verbose_name_plural='branches'

    def __str__(self):
        return '{}'.format(self.area)

class Person(models.Model):
    GENDER_CHOICES = [

        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    ]
    name=models.CharField(max_length=250,unique=True)
    dob=models.DateField(null=True,blank=True)
    age=models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=200, null=True)
    phoneno = models.CharField(max_length=250,unique=True)
    email=models.CharField(max_length=250,unique=True)
    address = models.TextField()
    district=models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    area=models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.name)

banckproject/credential_app/models.py
from django.db import models

# Create your models here.

banckproject/banckapp/forms.py
from django import forms

from .models import Branch, Person


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'class': 'form-control','type':'date'}),
            'phoneno': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'district': forms.Select(attrs={'class': 'form-control'}),
            'area': forms.Select(attrs={'class': 'form-control'}),
                  }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['area'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['area'].queryset = Branch.objects.filter(district_id=district_id).all()
            except (ValueError, TypeError):
                pass

banckproject/banckapp/views.py
# Create your views here.
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect
from .forms import PersonCreationForm
from .models import District,Branch,Person

# Create your views here.
def index(request):
    return render(request,"index.html")


def new(request):
    return render(request,'new_page.html')

def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('banckapp:submit')
    return render(request, 'submission_form.html', {'form': form})

def load_areas(request):
    district_id = request.GET.get('district_id')
    cities = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'area_dropdown_list.html', {'cities': cities})

def submit(request):
    return render(request,"submit.html")

banckproject/credential_app/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import redirect, render


# Create your views here.
def login(request):
    if request.method == "POST":
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid credentials")
            return redirect('credentials:login')

    return render(request,'login.html')

def register(request):
    if request.method == "POST":
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['password1']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('credentials:register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('credentials:login')
            
        else:
            messages.info(request,"incorrect password")
            return redirect('credentials:register')
        return redirect('credentials:login')
    return render (request,"register.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

banckproject/templates/area_dropdown_list.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.area }}</option>
{% endfor %}

banckproject/templates/login.html
<!DOCTYPE html> 
<html> 
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous" />
<title> Login Page </title>
<style> 
Body {
     
    background-size: cover;
    height: 200%;
    width:90%;
    justify-content: center;
    align-items: center;
}
button { 
    background-color: #d38a1c;
    color: #fff;
    font-size: 30px;
    width:50%;
    text-transform: uppercase;
    cursor: pointer;
    paddin Top:10px;
    margin:10px
         } 
 form { 
        
    } 
 input[type=text], input[type=password] { 
        width: 90%; 
        margin: 6px 0;
        padding: 12px 20px; 
       
       
        
    }
 button:hover { 
        opacity: 0.7; 
    } 
  .cancelbtn { 
        width: auto; 
        padding: 10px 18px;
        margin: 10px 5px;
    } 
      
   
 .container { 
        padding: 25px; 
        background-color: lightblue;
    } 

</style> 
</head>  
<body>  
    <br>
     <center> <h1>LoginForm </h1> </center>
     <br> 
    <form action="{% url 'credentials:login'%}" method="POST">
        {% csrf_token %}
        <div class="container"> 
            <label>Username : </label> 
            <input type="text" placeholder="Enter Username" name="username" required>
            <label>Password : </label> 
            <input type="password" placeholder="Enter Password" name="password" required>
            <div class="text-center">
                <Button><a href="{% url 'credentials:register' %}">Register</a></Button>
               </div>
           <center> <button type="submit">Login</button> </center>
            
        </div> 
    </form> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>   
</html>

banckproject/templates/new_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
          <br>
      <h1 class="head1" style="text-align:center;font-size:34px;color:blue;font-style:italic;font-weight:bold"><u>Form Submission</u></h1><br><br>
        </div>
        <img src="https://png.pngtree.com/png-clipart/20221001/original/pngtree-digital-internet-banking-application-for-financial-operation-png-image_8649134.png" alt="image" width="100%" height="450px">
        <br>
        <a href="{% url 'banckapp:person_add' %}" class="btn btn-warning" style="font-size:20px;margin-left:530px;">Please Fill The Form</a>
      </div>
</body>
</html>

banckproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous" />

    <title>Register Form</title>
  </head>
  <body>
    <section>
      <div class="container mt-5 pt-5">
        <div class="row">
          <div class="col-12 col-sm-7 col-md-6 m-auto">
            <div class="card border-0 shadow">
              <div class="card-body">
                <h1>Registertion</h1>
                <form action="{% url 'credentials:register'%}" method="POST">
                  {% csrf_token %}

                  <input type="text" name="username" id="" class="form-control my-4 py-2" placeholder="Username" />
                  <br>
                  <input type="password" name="password" id="" class="form-control my-4 py-2" placeholder="Password" /><br>
                  <input type="password" name="password1" id="" class="form-control my-4 py-2" placeholder="Repeat Password" /><br>
                  <div class="text-center mt-3">
                    <input type="submit" class="btn btn-primary">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% for msg in messages %}
      <h2><center>{{ msg }}</center></h2>
    {% endfor %}

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

banckproject/templates/submission_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            
            <img src="{% static 'assets/images/resources/2.jpg'%}" alt="image" width="100%" height="500px">
            <br>
            <br>
            <br>
            <form method="post" id="personForm" data-cities-url="{% url 'banckapp:ajax_load_areas' %}">
                {% csrf_token %}
                <div class="container">
                    {{ form.as_p }}
                    <div class="form-group row">
                        <div class="col-sm-2">Account Type</div>
                        <div class="col-sm-10">
                            <select>
                                <option value>Savings</option>
                                <option value>Current</option>
                            </select>
                        </div>
                    </div>

                    <br>
                    <div class="form-group row">
                        <div class="col-sm-2">Materials Provide</div>
                        <div class="col-sm-10">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck1">
                                <label class="form-check-label" for="gridCheck1">Debit Card </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck2">
                                <label class="form-check-label" for="gridCheck1">Credit Card </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck3">
                                <label class="form-check-label" for="gridCheck1">Cheque Book </label>
                            </div>
                        </div>
                    </div>
                    <br><br><br>
                    <input type="submit" class="btn btn-primary" value="Submit"
                        style="font-size:18px;margin-left:100px;">
                </div>
            </form>
        </div>
    </div>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
                $("#id_district").change(function () {
                    const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_areas` view
                    const districtId = $(this).val();  // get the selected district ID from the HTML input

                    $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= /persons/ajax/load-areas/ )
                        data: {
                            'district_id': districtId       // add the district id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the `load_cities` view function
                            $("#id_area").html(data);  // replace the contents of the area input with the data that came from the server

                        }
                    });

                });
            </script>
      

</body>

</html>

banckproject/templates/submit.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <h2 style="font-size:34px;font-weight:bold"><u><a 
        href="{% url 'credentials:logout'%}">Logout</a></u></h2>
     
      <div class="card">
       
            
       
     
      <div style="border-radius:200px; height:250px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
        <h1>success</h1>
      </div>
      
       
       
      </div>
      
      <a href="{% url 'banckapp:index' %}" style="text-align:center;font-size:25px;color:rgb(0, 89, 255);font-style:normal">Return Home Page</a>
     
    </body>
</html>